export default [
  {
    path: '/',
    component: '@/layouts/RootLayout',
    routes: [
      {
        path: '/home',
        name: '首页',
        layout: false,
        hideInMenu: true,
        component: './Home',
      },
      {
        path: '/settings',
        name: '设置',
        layout: false,
        hideInMenu: true,
        component: './Settings',
      },
      { path: '/practice', name: '练习', layout: false, component: './Practice' },
      {
        path: '/practicereading',
        name: '阅读练习',
        layout: false,
        hideInMenu: true,
        component: './PracticeReading',
      },
      {
        path: '/practicelistening',
        name: '听力练习',
        layout: false,
        hideInMenu: true,
        component: './PracticeListening',
      },
      {
        path: '/practicespeaking',
        name: '口语练习',
        layout: false,
        hideInMenu: true,
        component: './PracticeSpeaking',
      },
      {
        path: '/practicewriting',
        name: '写作练习',
        layout: false,
        hideInMenu: true,
        component: './PracticeWriting',
      },
      {
        path: '/reviewreading',
        name: '阅读复习',
        layout: false,
        hideInMenu: true,
        component: './ReviewReading',
      },
      {
        path: '/reviewlistening',
        name: '听力复习',
        layout: false,
        hideInMenu: true,
        component: './ReviewListening',
      },
      {
        path: '/reviewspeaking',
        name: '口语复习',
        layout: false,
        hideInMenu: true,
        component: './ReviewSpeaking',
      },
      {
        path: '/reviewwriting',
        name: '写作复习',
        layout: false,
        hideInMenu: true,
        component: './ReviewWriting',
      },
      {
        path: '/intensivelistening',
        name: '精听训练',
        layout: false,
        hideInMenu: true,
        component: './IntensiveListening',
      },
      { path: '/mockexam', name: '模考', layout: false, component: './MockExam' },
      {
        path: '/mockreading',
        name: '阅读模考',
        layout: false,
        hideInMenu: true,
        component: './MockReading',
      },
      {
        path: '/mockreadscore',
        name: '阅读模考分数',
        layout: false,
        hideInMenu: true,
        component: './MockReadScore',
      },
      {
        path: '/mockreadreview',
        name: '阅读模考回顾',
        layout: false,
        hideInMenu: true,
        component: './MockReadReview',
      },
      { path: '/pricing', name: '价格', layout: false, component: './Pricing' },
      { path: '/wrong', name: '错题', layout: false, component: './WrongQuestions' },
      { path: '/', redirect: '/home' },
      { redirect: '/home' },
    ],
  },
  { redirect: '/home' },
]
